import type { Role } from "./types";

/**
 * Every role on the resume, in the resume's order, followed by the two contracts Samuel added
 * directly in September 2026 (Lotus Bank and WeTribe), which the resume predates.
 * `lib/work.ts` sorts them for display.
 *
 * Highlights restate the resume's bullets with the adjectives taken out. Figures appear only
 * where the resume states them, as `metric`. If a claim is not on the resume it does not go here.
 *
 * Store links and screenshots are slots on every role. To fill one in:
 *
 *   stores: {
 *     appStore: "https://apps.apple.com/ng/app/...",
 *     googlePlay: "https://play.google.com/store/apps/details?id=...",
 *   },
 *   shots: [
 *     { src: "/work/firstbank-ghana/home.png", alt: "Home screen with account balances" },
 *     { src: "/work/firstbank-ghana/transfer.png", alt: "PAPSS cross-border transfer", caption: "PAPSS transfer" },
 *   ],
 *
 * Image files go in `public/work/<slug>/`. Leave a slot as null or [] and the page omits it.
 */
export const roles: Role[] = [
  {
    slug: "mintyn",
    company: "Mintyn Bank",
    title: "Senior Mobile Engineer",
    start: "2026-03",
    end: null,
    sector: "Banking",
    summary:
      "Building financial modules in Swift and SwiftUI, with biometric security and caching for high-traffic transactions.",
    highlights: [
      "Architect and build financial modules in Swift and SwiftUI that integrate with the bank's existing infrastructure.",
      "Lead the migration of legacy components to SwiftUI, improving UI responsiveness, maintainability and reuse.",
      "Integrate secure authentication, including biometrics, to protect financial data and meet regulatory requirements.",
      "Cut network latency on high-traffic banking transactions with caching strategies.",
      "Mentor junior engineers on Swift and SwiftUI state management.",
    ],
    stack: ["Swift", "SwiftUI", "Biometrics"],
    stores: {
      appStore: "https://apps.apple.com/ng/app/mintyn-everything-finance/id1470644607",
      googlePlay: "https://play.google.com/store/apps/details?id=com.mintfintech.app",
      web: "https://mintyn.com",
    },
    shots: [],
    tone: "ink",
    tags: ["Swift", "SwiftUI", "Biometrics"],
    featured: true,
  },
  {
    slug: "firstbank-ghana",
    company: "FirstBank",
    context: "Ghana subsidiary",
    title: "Senior Mobile Engineer",
    terms: "Contract",
    start: "2025-02",
    end: "2026-03",
    sector: "Banking",
    summary:
      "Key features for the official FirstBank Ghana app, including its first live PAPSS integration and an offline soft token that replaced hardware tokens.",
    highlights: [
      "Led key feature development for the FirstBank Ghana app, used by hundreds of thousands of retail and corporate customers.",
      "Designed and shipped an offline-capable, TOTP-based soft-token 2FA that replaced hardware tokens and removed the cost of distributing them.",
      "Delivered the app's first live PAPSS integration: instant cross-border payments in GHS and other African currencies, with full reconciliation and retry logic.",
      "Built real-time email and SMS transaction alerts against FirstBank's on-premise .NET backend and Ghanaian SMS aggregators.",
      "Built offline-first transaction queuing, certificate pinning, jailbreak and root detection, and encrypted storage with Hive and flutter_secure_storage.",
      "Kept the app within Bank of Ghana cybersecurity guidelines, NDPR and PCI-DSS through code review, penetration testing and static analysis.",
      "Worked daily with the .NET Core, Oracle and Temenos T24 teams to ship zero-downtime releases.",
    ],
    stack: ["Flutter", "Hive", "flutter_secure_storage", "PAPSS", ".NET Core", "Temenos T24"],
    metric: { value: "100%", label: "adoption of the soft-token 2FA in the pilot phase" },
    stores: {
      appStore: "https://apps.apple.com/gh/app/firstbank-ghana-mobile-app/id1558479443",
      googlePlay: "https://play.google.com/store/apps/details?id=com.fbndl.fbnmobileghana",
      web: "https://www.fbnbankghana.com",
    },
    shots: [],
    tone: "moss",
    tags: ["Flutter", "PAPSS", "TOTP 2FA", "Offline-first"],
    featured: true,
  },
  {
    slug: "ojanow",
    company: "OjaNow",
    title: "Senior Mobile Engineer",
    start: "2025-03",
    end: "2025-09",
    sector: "Commerce",
    summary: "Flutter apps for 24/7 on-demand delivery of essentials in Nigeria's quick-commerce market.",
    highlights: [
      "Built and maintained cross-platform Flutter apps for instant, around-the-clock delivery of essentials.",
      "Designed and implemented interfaces with cross-functional teams for the on-demand delivery flow.",
      "Improved app performance and integrated APIs to speed up delivery.",
      "Shipped optimised delivery routes to reduce the service's carbon footprint.",
      "Worked in agile sprints with planning and code review.",
      "Brought AI-assisted development (GitHub Copilot, ChatGPT) into the team's workflow.",
    ],
    stack: ["Flutter"],
    stores: {
      appStore: "https://apps.apple.com/ng/app/ojanow/id6444134665",
      googlePlay: "https://play.google.com/store/apps/details?id=com.ojanow.app.oja",
      web: "https://ojanowapp.com",
    },
    shots: [],
    tone: "clay",
    tags: ["Flutter", "Q-commerce"],
  },
  {
    slug: "ngss",
    company: "NGSS",
    context: "Nester Global Solution Service",
    title: "Senior Flutter Engineer",
    start: "2024-06",
    end: "2025-03",
    sector: "Identity",
    summary:
      "Flutter identity verification for real-time KYC, integrating APIs that cover more than 200 million identities in Nigeria.",
    highlights: [
      "Built and maintained Flutter identity verification products for real-time KYC checks by businesses and institutions.",
      "Integrated the APIs behind verification of over 200 million identities in Nigeria.",
      "Reworked the verification flows to shorten onboarding.",
      "Implemented secure handling of sensitive data with the backend team.",
    ],
    stack: ["Flutter"],
    metric: { value: "200M+", label: "identities covered by the verification APIs integrated" },
    stores: { appStore: null, googlePlay: null, web: "https://nesterverify.com" },
    shots: [],
    tone: "slate",
    tags: ["Flutter", "KYC", "Identity"],
    featured: true,
  },
  {
    slug: "citigo",
    company: "Citigo",
    title: "Lead Flutter Engineer",
    start: "2024-02",
    end: "2024-08",
    sector: "Mobility",
    summary:
      "Led the core of a ride-hailing app in Flutter: live location tracking, driver-rider matching and fare calculation.",
    highlights: [
      "Led development of the core ride-hailing features: real-time location tracking, driver-rider matching and fare calculation.",
      "Integrated mapping APIs for in-app navigation, reducing reliance on external navigation apps.",
      "Improved the driver-rider matching, cutting user wait times by 20%.",
      "Worked with the backend team on data flow and secure in-app transactions.",
    ],
    stack: ["Flutter", "Mapping APIs"],
    metric: { value: "20%", label: "decrease in user wait times from better matching" },
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "bone",
    tags: ["Flutter", "Maps", "Real-time"],
    featured: true,
  },
  {
    slug: "myaza",
    company: "MyAza",
    title: "Flutter Engineer",
    start: "2023-10",
    end: "2024-07",
    sector: "Payments",
    summary: "Secure payment UI, authentication and money transfer for a payment processing app.",
    highlights: [
      "Designed and built Flutter UI components for the payment processing app.",
      "Integrated payment gateways and financial APIs for money transfers.",
      "Implemented authentication, account management and money transfer features.",
      "Worked with QA to find and resolve bugs before release.",
      "Optimised transaction code, making transactions 15% faster.",
    ],
    stack: ["Flutter", "Payment gateways"],
    metric: { value: "15%", label: "faster transaction processing" },
    stores: {
      appStore: "https://apps.apple.com/ng/app/myaza-africas-money-app/id6450796310",
      googlePlay: "https://play.google.com/store/apps/details?id=co.myaza",
      web: "https://myaza.co",
    },
    shots: [],
    tone: "moss",
    tags: ["Flutter", "Payments"],
  },
  {
    slug: "cornie-health",
    company: "Cornie Health",
    product: "E-lerrah",
    title: "Lead Flutter Developer",
    start: "2024-07",
    end: "2024-09",
    sector: "Health",
    summary: "Led E-lerrah, a medical appointment booking app, from doctor search to secure payment. Launched on time.",
    highlights: [
      "Led development of E-lerrah, a Flutter app for booking medical appointments.",
      "Built registration, scheduling, doctor search and secure payment with the design and backend teams.",
      "Handled sensitive health data to HIPAA requirements.",
      "Launched on time and within budget.",
      "Improved data fetching for faster loading.",
    ],
    stack: ["Flutter"],
    stores: { appStore: null, googlePlay: null, web: "https://corniehealth.com" },
    shots: [],
    tone: "clay",
    tags: ["Flutter", "Healthtech"],
  },
  {
    slug: "uobis",
    company: "Uobis",
    title: "Flutter Mobile Developer",
    start: "2022-04",
    end: "2023-10",
    sector: null,
    summary: "Code review, release quality and mentoring on a Flutter team.",
    highlights: [
      "Ran regular code reviews and set the team's coding standards.",
      "Worked with QA to test and resolve issues before each release.",
      "Mentored junior developers on Flutter practice and problem solving.",
      "Organised internal knowledge-sharing sessions on Flutter.",
    ],
    stack: ["Flutter"],
    stores: { appStore: null, googlePlay: null, web: "https://uobis.com" },
    shots: [],
    tone: "slate",
    tags: ["Flutter", "Mentoring"],
  },
  {
    slug: "david-consult",
    company: "David Consult",
    title: "Mobile Engineer",
    terms: "Internship",
    start: "2019-03",
    end: "2021-10",
    sector: null,
    summary: "Built a Flutter app end to end, and cut its loading time by 30%.",
    highlights: [
      "Built a Flutter app end to end.",
      "Kept the code modular and maintainable.",
      "Turned design specifications into responsive interfaces with the UX/UI designers.",
      "Integrated third-party APIs.",
      "Profiled the app and fixed the bottlenecks, cutting loading times by 30%.",
      "Optimised data fetching and processing with the backend developers.",
    ],
    stack: ["Flutter"],
    metric: { value: "30%", label: "reduction in app loading times" },
    stores: { appStore: null, googlePlay: null, web: "https://www.davidconsult.com.ng" },
    shots: [],
    tone: "bone",
    tags: ["Flutter"],
  },
  {
    slug: "lotus-bank",
    company: "Lotus Bank",
    title: "Senior Mobile Engineer",
    terms: "Contract",
    start: "2026-08",
    end: "2026-09",
    sector: "Banking",
    summary:
      "Flutter work on Lotus Bank's corporate (CIB) and retail (RIB) banking apps: payment approval flows, release-safe logging, an iOS engine migration and build tooling for every flavor.",
    /** From Samuel's work log for the contract. Completed items only; nothing still in progress. */
    highlights: [
      "Worked in Flutter on Lotus Business, the bank's corporate internet banking (CIB) app, and the Lotus Bank App for retail customers (RIB).",
      "Built a central, release-safe logging utility so no sensitive data is ever printed in production builds, replacing scattered print statements.",
      "Migrated the bill payment approval flow from the deprecated DioError to DioException, with bug fixes and cleanup along the way.",
      "Fixed missing loading states across the bill, airtime, electricity, data and collection approval screens.",
      "Added debug logging for interbank name-enquiry requests and reviewed the name-enquiry and approval API contracts with the backend team.",
      "Moved the iOS AppDelegate to Flutter's new plugin registration pattern and added a Scene Manifest for the new engine lifecycle.",
      "Standardised the local setup (FVM, VS Code launch settings, DevTools options) and added a Makefile that runs and builds all five flavors: dev, staging, pilot, UAT and production.",
      "Traced a name-enquiry failure in the UAT environment to a base-URL misconfiguration and worked with the backend team on the sandbox integration.",
    ],
    stack: ["Flutter", "Dio", "FVM", "iOS", "Make"],
    stores: {
      name: "Lotus Business (CIB)",
      appStore: "https://apps.apple.com/ng/app/lotus-business/id6474792094",
      googlePlay: "https://play.google.com/store/apps/details?id=lotus_business2.lotus.mgr",
      web: "https://www.lotusbank.com",
    },
    moreApps: [
      {
        name: "Lotus Bank App (RIB)",
        appStore: "https://apps.apple.com/ng/app/lotus-bank-app/id1599550703",
        googlePlay: "https://play.google.com/store/apps/details?id=com.lotusbank.ibank",
      },
    ],
    shots: [],
    tone: "slate",
    tags: ["Flutter", "CIB", "RIB", "Approvals"],
  },
  {
    slug: "wetribe",
    company: "WeTribe",
    context: "TribeAccess Inc.",
    title: "Senior Mobile Engineer",
    terms: "Contract",
    start: "2024-09",
    end: "2025-11",
    sector: "Events",
    summary:
      "Flutter work on WeTribe ahead of its January 2026 launch: a Canadian app for finding events on a live map, buying tickets in the app, meeting other event-goers and hosting events.",
    /**
     * DRAFT. Samuel asked for these to be written from research on the product (App Store
     * listing, September 2026) rather than a work log. Each maps to a feature the app ships;
     * confirm with Samuel which ones he built and trim the rest.
     */
    highlights: [
      "Built Flutter features for WeTribe, the events app from TribeAccess Inc. in Canada, in the run-up to its public launch on the App Store and Google Play in January 2026.",
      "Worked on the real-time live map that shows events happening near the user, and on recommendations tailored to interests and location.",
      "Worked on secure in-app ticket checkout, so people can buy tickets without leaving the app.",
      "Worked on the host side: creating events, managing ticket sales and tracking how each event performs.",
      "Worked on the social layer that helps event-goers find and connect with people who share their interests.",
    ],
    stack: ["Flutter"],
    stores: {
      appStore: "https://apps.apple.com/ca/app/wetribe/id6746691206",
      googlePlay: "https://play.google.com/store/apps/details?id=com.tribe.org.tribe",
      web: "https://wetribe.io",
    },
    shots: [],
    tone: "clay",
    tags: ["Flutter", "Live map", "Ticketing"],
  },
];
