import type { Role } from "./types";

/**
 * Every role on the resume, in the resume's order. `lib/work.ts` sorts them for display.
 *
 * Highlights restate the resume's bullets with the adjectives taken out. Figures appear only
 * where the resume states them, as `metric`. If a claim is not on the resume it does not go here.
 *
 * Store links and screenshots are slots on every role. To fill one in:
 *
 *   stores: {
 *     appStore: "https://apps.apple.com/ng/app/...",
 *     googlePlay: "https://play.google.com/store/apps/details?id=...",
 *   },
 *   shots: [
 *     { src: "/work/firstbank-ghana/home.png", alt: "Home screen with account balances" },
 *     { src: "/work/firstbank-ghana/transfer.png", alt: "PAPSS cross-border transfer", caption: "PAPSS transfer" },
 *   ],
 *
 * Image files go in `public/work/<slug>/`. Leave a slot as null or [] and the page omits it.
 */
export const roles: Role[] = [
  {
    slug: "mintyn",
    company: "Mintyn Bank",
    title: "Senior Mobile Engineer",
    start: "2026-03",
    end: null,
    sector: "Banking",
    summary:
      "Building financial modules in Swift and SwiftUI, with biometric security and caching for high-traffic transactions.",
    highlights: [
      "Architect and build financial modules in Swift and SwiftUI that integrate with the bank's existing infrastructure.",
      "Lead the migration of legacy components to SwiftUI, improving UI responsiveness, maintainability and reuse.",
      "Integrate secure authentication, including biometrics, to protect financial data and meet regulatory requirements.",
      "Cut network latency on high-traffic banking transactions with caching strategies.",
      "Mentor junior engineers on Swift and SwiftUI state management.",
    ],
    stack: ["Swift", "SwiftUI", "Biometrics"],
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "ink",
    tags: ["Swift", "SwiftUI", "Biometrics"],
    featured: true,
  },
  {
    slug: "firstbank-ghana",
    company: "FirstBank",
    context: "Ghana subsidiary",
    title: "Senior Mobile Engineer",
    terms: "Contract",
    start: "2025-02",
    end: "2026-03",
    sector: "Banking",
    summary:
      "Key features for the official FirstBank Ghana app, including its first live PAPSS integration and an offline soft token that replaced hardware tokens.",
    highlights: [
      "Led key feature development for the FirstBank Ghana app, used by hundreds of thousands of retail and corporate customers.",
      "Designed and shipped an offline-capable, TOTP-based soft-token 2FA that replaced hardware tokens and removed the cost of distributing them.",
      "Delivered the app's first live PAPSS integration: instant cross-border payments in GHS and other African currencies, with full reconciliation and retry logic.",
      "Built real-time email and SMS transaction alerts against FirstBank's on-premise .NET backend and Ghanaian SMS aggregators.",
      "Built offline-first transaction queuing, certificate pinning, jailbreak and root detection, and encrypted storage with Hive and flutter_secure_storage.",
      "Kept the app within Bank of Ghana cybersecurity guidelines, NDPR and PCI-DSS through code review, penetration testing and static analysis.",
      "Worked daily with the .NET Core, Oracle and Temenos T24 teams to ship zero-downtime releases.",
    ],
    stack: ["Flutter", "Hive", "flutter_secure_storage", "PAPSS", ".NET Core", "Temenos T24"],
    metric: { value: "100%", label: "adoption of the soft-token 2FA in the pilot phase" },
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "moss",
    tags: ["Flutter", "PAPSS", "TOTP 2FA", "Offline-first"],
    featured: true,
  },
  {
    slug: "ojanow",
    company: "OjaNow",
    title: "Senior Mobile Engineer",
    start: "2025-03",
    end: "2025-09",
    sector: "Commerce",
    summary: "Flutter apps for 24/7 on-demand delivery of essentials in Nigeria's quick-commerce market.",
    highlights: [
      "Built and maintained cross-platform Flutter apps for instant, around-the-clock delivery of essentials.",
      "Designed and implemented interfaces with cross-functional teams for the on-demand delivery flow.",
      "Improved app performance and integrated APIs to speed up delivery.",
      "Shipped optimised delivery routes to reduce the service's carbon footprint.",
      "Worked in agile sprints with planning and code review.",
      "Brought AI-assisted development (GitHub Copilot, ChatGPT) into the team's workflow.",
    ],
    stack: ["Flutter"],
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "clay",
    tags: ["Flutter", "Q-commerce"],
  },
  {
    slug: "ngss",
    company: "NGSS",
    context: "Nester Global Solution Service",
    title: "Senior Flutter Engineer",
    start: "2024-06",
    end: "2025-03",
    sector: "Identity",
    summary:
      "Flutter identity verification for real-time KYC, integrating APIs that cover more than 200 million identities in Nigeria.",
    highlights: [
      "Built and maintained Flutter identity verification products for real-time KYC checks by businesses and institutions.",
      "Integrated the APIs behind verification of over 200 million identities in Nigeria.",
      "Reworked the verification flows to shorten onboarding.",
      "Implemented secure handling of sensitive data with the backend team.",
    ],
    stack: ["Flutter"],
    metric: { value: "200M+", label: "identities covered by the verification APIs integrated" },
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "slate",
    tags: ["Flutter", "KYC", "Identity"],
    featured: true,
  },
  {
    slug: "citigo",
    company: "Citigo",
    title: "Lead Flutter Engineer",
    start: "2024-02",
    end: "2024-08",
    sector: "Mobility",
    summary:
      "Led the core of a ride-hailing app in Flutter: live location tracking, driver-rider matching and fare calculation.",
    highlights: [
      "Led development of the core ride-hailing features: real-time location tracking, driver-rider matching and fare calculation.",
      "Integrated mapping APIs for in-app navigation, reducing reliance on external navigation apps.",
      "Improved the driver-rider matching, cutting user wait times by 20%.",
      "Worked with the backend team on data flow and secure in-app transactions.",
    ],
    stack: ["Flutter", "Mapping APIs"],
    metric: { value: "20%", label: "decrease in user wait times from better matching" },
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "bone",
    tags: ["Flutter", "Maps", "Real-time"],
    featured: true,
  },
  {
    slug: "myaza",
    company: "MyAza",
    title: "Flutter Engineer",
    start: "2023-10",
    end: "2024-07",
    sector: "Payments",
    summary: "Secure payment UI, authentication and money transfer for a payment processing app.",
    highlights: [
      "Designed and built Flutter UI components for the payment processing app.",
      "Integrated payment gateways and financial APIs for money transfers.",
      "Implemented authentication, account management and money transfer features.",
      "Worked with QA to find and resolve bugs before release.",
      "Optimised transaction code, making transactions 15% faster.",
    ],
    stack: ["Flutter", "Payment gateways"],
    metric: { value: "15%", label: "faster transaction processing" },
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "moss",
    tags: ["Flutter", "Payments"],
  },
  {
    slug: "cornie-health",
    company: "Cornie Health",
    product: "E-lerrah",
    title: "Lead Flutter Developer",
    start: "2024-07",
    end: "2024-09",
    sector: "Health",
    summary: "Led E-lerrah, a medical appointment booking app, from doctor search to secure payment. Launched on time.",
    highlights: [
      "Led development of E-lerrah, a Flutter app for booking medical appointments.",
      "Built registration, scheduling, doctor search and secure payment with the design and backend teams.",
      "Handled sensitive health data to HIPAA requirements.",
      "Launched on time and within budget.",
      "Improved data fetching for faster loading.",
    ],
    stack: ["Flutter"],
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "clay",
    tags: ["Flutter", "Healthtech"],
  },
  {
    slug: "uobis",
    company: "Uobis",
    title: "Flutter Mobile Developer",
    start: "2022-04",
    end: "2023-10",
    sector: null,
    summary: "Code review, release quality and mentoring on a Flutter team.",
    highlights: [
      "Ran regular code reviews and set the team's coding standards.",
      "Worked with QA to test and resolve issues before each release.",
      "Mentored junior developers on Flutter practice and problem solving.",
      "Organised internal knowledge-sharing sessions on Flutter.",
    ],
    stack: ["Flutter"],
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "slate",
    tags: ["Flutter", "Mentoring"],
  },
  {
    slug: "david-consult",
    company: "David Consult",
    title: "Mobile Engineer",
    terms: "Internship",
    start: "2019-03",
    end: "2021-10",
    sector: null,
    summary: "Built a Flutter app end to end, and cut its loading time by 30%.",
    highlights: [
      "Built a Flutter app end to end.",
      "Kept the code modular and maintainable.",
      "Turned design specifications into responsive interfaces with the UX/UI designers.",
      "Integrated third-party APIs.",
      "Profiled the app and fixed the bottlenecks, cutting loading times by 30%.",
      "Optimised data fetching and processing with the backend developers.",
    ],
    stack: ["Flutter"],
    metric: { value: "30%", label: "reduction in app loading times" },
    stores: { appStore: null, googlePlay: null },
    shots: [],
    tone: "bone",
    tags: ["Flutter"],
  },
];
